name: state_management_grand_tour
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.22.0
  get_it: ^1.0.3+1
  bloc: ^0.14.2
  flutter_bloc: ^0.15.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

